---
- name: Add host entries to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  loop:
    - "{{ master_ip }} {{ master_hostname }}"
    # - "{{ worker1_ip }} {{ worker1_hostname }}"
    # - "{{ worker2_ip }} {{ worker2_hostname }}"